name: release
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: |
          dotnet build TimestampVersion/TimestampVersion.csproj -c release -o build
          dotnet build/tsv.dll --xml-files TimestampVersion/TimestampVersion.csproj --env-file $env:GITHUB_ENV
          dotnet publish TimestampVersion/TimestampVersion.csproj -r win-x64 -p:PublishSingleFile=true --no-self-contained -c release -o publish
          dotnet publish TimestampVersion/TimestampVersion.csproj -r linux-x64 -p:PublishSingleFile=true --no-self-contained -c release -o publish
          dotnet pack TimestampVersion/TimestampVersion.csproj -c release -p:AssemblyName=TimestampVersion -o nuget
          dotnet nuget push "nuget/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json

      - name: Tag and Release
        uses: jasondavis303/tag-and-release-and-upload@v1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          version: v${{ env.TIMESTAMP_VERSION }}          
          assets: '[ "./publish/tsv.exe", "./publish/tsv" ]'
          overwrite: true
