name: release
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: First Build
        run: |
          dotnet build -c release -o build
          dotnet build/TimestampVersion.dll --xml-file TimestampVersion/TimestampVersion.csproj
          dotnet pack -c release -o .
